### ISSUE TITLE
Support security schema rendering

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-theme-openapi#12]
My API has a security scheme defined, such as the following

```
    "security": [
      {
        "ApiKeyAuth": []
      }
    ],
    "components": {
      "securitySchemes": {
        "ApiKeyAuth": {
          "type": "apiKey",
          "in": "header",
          "name": "Authorization"
        }
      },
```

Which can then be interpereted as being applied globally, or overridden on a per route level, such as by defining

```
        "security": [
          {
            "ApiKeyAuth": []
          }
        ]
```

For the route.

Per the spec at https://swagger.io/docs/specification/authentication/

As far as I can see this is not currently represeented anywhere by the component

![image](https://github.com/user-attachments/assets/c02bee94-39cf-4e5e-8f28-dad53c98054e)

https://gist.github.com/addshore/e6b973939739e25902025bf1667e69a1 is an example API spec that demonstrates this feature and thus issue

**Comment by enzonotario** [comment]
It's not implemented yet, and it's a bit more complex since it should be setted globally. I don't plan to work on this so far.

It's also missing Header Parameters, but this could be more simpler to implement, and could be a workaround for this Issue since the Auth is just a Header Parameter.

As always, PRs are welcome.
