### ISSUE TITLE
Too many response codes results in element overlap

### ISSUE THREAD

**Issue by addshore** [enzonotario/vitepress-theme-openapi#46]
Example

![image](https://github.com/user-attachments/assets/f5b2b5d7-dc42-4b59-8a86-cf74338839a5)

200,400,401,429,500

Perhaps it could / should be a drop down if there are more than 4?

**Comment by enzonotario** [comment]
I've made it configurable via `useTheme` composable. As always, it can be configured **per page**, or globally in VitePress Theme config. Can you please check it in #51?

Another great improvement would be to auto switch to Select or Tabs based in the space available in viewport (when it overflows the `x` space, auto-switch to Select alternative; otherwise use Tabs). But I think this would be a little more complex and could be a future feature.
